apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  type: ClusterIP
status:
  loadBalancer: {}
